-- ==========================================================
-- Migration: FIFO & Purchase Batch / Lot Costing
-- سیستەمی وەجبەی کڕین و تێچووی FIFO
-- Business: سەنگەر زمارەیی و جێگر زمارەیی
-- ==========================================================

-- 1. INVENTORY BATCHES TABLE
CREATE TABLE IF NOT EXISTS inventory_batches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
  purchase_id BIGINT REFERENCES purchases(id) ON DELETE SET NULL,
  purchase_item_id BIGINT REFERENCES purchase_items(id) ON DELETE SET NULL,
  supplier_id BIGINT REFERENCES suppliers(id) ON DELETE SET NULL,
  batch_type VARCHAR(50) NOT NULL DEFAULT 'PURCHASE', -- 'PURCHASE', 'OPENING_BALANCE', 'MANUAL_ADJUSTMENT', 'RETURN', 'CORRECTION'
  batch_number VARCHAR(100),
  original_quantity INT NOT NULL CHECK (original_quantity > 0),
  remaining_quantity INT NOT NULL CHECK (remaining_quantity >= 0 AND remaining_quantity <= original_quantity),
  unit_cost BIGINT NOT NULL CHECK (unit_cost >= 0),
  purchase_date DATE NOT NULL DEFAULT CURRENT_DATE,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 2. SALE ITEM COST ALLOCATIONS TABLE (FIFO COGS Traceability)
CREATE TABLE IF NOT EXISTS sale_item_cost_allocations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sale_id BIGINT NOT NULL REFERENCES sales(id) ON DELETE CASCADE,
  sale_item_id BIGINT NOT NULL REFERENCES sale_items(id) ON DELETE CASCADE,
  product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
  batch_id BIGINT NOT NULL REFERENCES inventory_batches(id) ON DELETE RESTRICT,
  quantity INT NOT NULL CHECK (quantity > 0),
  unit_cost BIGINT NOT NULL CHECK (unit_cost >= 0),
  total_cost BIGINT NOT NULL CHECK (total_cost >= 0),
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 3. SALE RETURN COST ALLOCATIONS TABLE
CREATE TABLE IF NOT EXISTS sale_return_cost_allocations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  return_id BIGINT NOT NULL REFERENCES returns(id) ON DELETE CASCADE,
  return_item_id BIGINT NOT NULL REFERENCES return_items(id) ON DELETE CASCADE,
  sale_item_cost_allocation_id BIGINT REFERENCES sale_item_cost_allocations(id) ON DELETE SET NULL,
  batch_id BIGINT NOT NULL REFERENCES inventory_batches(id) ON DELETE RESTRICT,
  quantity INT NOT NULL CHECK (quantity > 0),
  unit_cost BIGINT NOT NULL CHECK (unit_cost >= 0),
  total_cost BIGINT NOT NULL CHECK (total_cost >= 0),
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 4. PERFORMANCE INDEXES
CREATE INDEX IF NOT EXISTS idx_inv_batches_prod_rem ON inventory_batches (product_id, remaining_quantity);
CREATE INDEX IF NOT EXISTS idx_inv_batches_prod_fifo ON inventory_batches (product_id, purchase_date ASC, id ASC);
CREATE INDEX IF NOT EXISTS idx_inv_batches_purchase ON inventory_batches (purchase_id);
CREATE INDEX IF NOT EXISTS idx_cost_alloc_sale ON sale_item_cost_allocations (sale_id);
CREATE INDEX IF NOT EXISTS idx_cost_alloc_sale_item ON sale_item_cost_allocations (sale_item_id);
CREATE INDEX IF NOT EXISTS idx_cost_alloc_batch ON sale_item_cost_allocations (batch_id);
CREATE INDEX IF NOT EXISTS idx_ret_cost_alloc_ret ON sale_return_cost_allocations (return_id);

-- 5. IDEMPOTENT OPENING BALANCE MIGRATION FOR EXISTING INVENTORY
-- Converts existing positive product quantities into initial opening balance batches
INSERT INTO inventory_batches (
  product_id,
  supplier_id,
  batch_type,
  batch_number,
  original_quantity,
  remaining_quantity,
  unit_cost,
  purchase_date,
  notes,
  created_at,
  updated_at
)
SELECT
  p.id,
  p.supplier_id,
  'OPENING_BALANCE',
  'INIT-' || p.id || '-' || TO_CHAR(CURRENT_DATE, 'YYYYMMDD'),
  p.quantity,
  p.quantity,
  p.purchase_price,
  COALESCE(DATE(p.created_at), CURRENT_DATE),
  'مەخزەنی سەرەتایی کاتی کاراکردنی سیستەمی وەجبە (FIFO)',
  NOW(),
  NOW()
FROM products p
WHERE p.quantity > 0
  AND NOT EXISTS (
    SELECT 1 FROM inventory_batches b WHERE b.product_id = p.id
  );
